name: Nodejs CI

on:
  push: 
    branches: [main]

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_KEY}}
          script: |
            pm2 stop all || true
            cd /home/ubuntu/Deploy-on-EC2
            git pull origin main 
            npm install 
            pm2 restart app